Update terraform-pipeline.yml

diff --git a/.github/workflows/terraform-pipeline.yml b/.github/workflows/terraform-pipeline.yml
--- a/.github/workflows/terraform-pipeline.yml
+++ b/.github/workflows/terraform-pipeline.yml
@@ -91,6 +91,11 @@ jobs:
           app_object_id       = "b2288382-af60-408b-9389-22ea420a94d9"
           EOF
 
+      - name: Import existing Key Vault Access Policy if exists
+        working-directory: terraform-provisioner
+        run: |
+          terraform import -allow-missing azurerm_key_vault_access_policy.policy "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ needs.bootstrap.outputs.rg }}/providers/Microsoft.KeyVault/vaults/${{ needs.bootstrap.outputs.kv }}/objectId/${{ secrets.APP_OBJECT_ID }}" || echo "Access Policy not found, will be created"
+
       - name: Import existing Key Vault Key if it exists
         working-directory: terraform-provisioner
         run: |
